@startuml

title Basic Structure

(*) --> [action] "Store.dispatch()"

"View event" -> [action] "Store.dispatch()"
-> "Middleware()"
--> [  ] "next()"
--> [next chain] "Middleware()"
-> "Store.dispatch()"

"next()" --> [chain complete] "Store.handleAction()"
--> [call systems] ==RUNSYSTEMS==
--> [action] "System.handle()"
-> [event] "StateManager.push()"
-> [ ] "System.handle()"
--> ==COMMITSYSTEMS==
--> "StateManager.commit()"
-> "StateManager.shift()"

if "Event exists?" then
  -> [yes] "StateManager.emit()"
  --> ==EMITEVENT==
  --> [event] "callback()"
  --> ==CHANGEEVENT==
  --> [event] "ChangeController.handle()"
  --> "StateManager.shift()"
else
  --> [no] "Exit"
endif

@enduml
