@startuml

title Basic Structure

(*) --> [create] Action

View -> [create] Action
-> [dispatch] Middleware
-> [next] Middleware
--> [dispatch] Middleware

Middleware --> [done] System
System -> [next] System
System --> [set] Validator

Validator -> [next] Validator
--> [done] Cache
-> [next] Cache
--> [write] System

System --> [done] View
View -> (*)


@enduml
