@startuml

title Basic Structure

(*) --> [create] Action

View -> [create] Action
-> [dispatch] Engine
-> [dispatch] Middleware
-> [next] Middleware
-> [dispatch] Engine

Middleware --> [done] System
System -> [next] System
System --> [edit] Entity
System --> [done] Queue

Entity -> [edit] Component

Component --> [event] Queue
Entity --> [event] Queue
note right: queues events and emits only once.

Queue --> [dispatch] Handler

Handler --> [update] View
Handler -> (*)


@enduml
